music/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),

    url(r'^register/$', views.register_view, name='register'),

    url(r'^login/$', views.login_view, name='login'),

    # music/<some album id>
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    #url(r'^album/add/$', views.CreateAlbum.as_view(), name='add-album'),

    url(r'^logout/$', logout, {'next_page': '/music/login/'}, name='logout')

    # music/<album id>/favorite/
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

test_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    logo = models.CharField(max_length=1000)

    # called after the creating a new Album object, which sends user to the album's detail page
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title + ' - ' + self.album.title + ' - ' + self.album.artist

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

music/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from .models import Album


# Create your views here.
def index(request):
    # if not request.user.is_authenticated():
    #     return redirect('music:login')
    # else:
        albums = Album.objects.all()
        context = {'albums': albums}
        return render(request, 'music/index.html', context)


def detail(request, album_id):
    if not request.user.is_authenticated():
        return redirect('music:login')

    album = get_object_or_404(Album, id=album_id)
    return render(request, 'music/detail.html', {'album': album})


def login_view(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('music:index')
        else:
            context = {'error_message': 'Username or password are incorrect', 'username': username}
            return render(request, 'music/login_form.html', context)

    return render(request, 'music/login_form.html')


def register_view(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        errors = is_valid(username, email, password)
        if errors is None:
            user = User.objects.create_user(username, email, password)
            user.save()
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                albums = Album.object.all()
                return render(request, 'music/index.html', {'albums': albums})
        else:
            errors['username'] = username
            errors['email'] = email
            return render(request, 'music/registration_form.html', errors)

    return render(request, 'music/registration_form.html')


def is_valid(username, email, password):
    errors = {'username_error': None, 'email_error': None, 'password_error': None}
    if not username:
        errors['username_error'] = 'Username field cannot be blank'

    if not email:
        errors['email_error'] = 'Email field cannot be blank'

    if not password:
        errors['password_error'] = 'Password field cannot be blank'

    for value in errors:
        if value is None:
            continue
        else:
            return errors

    return None


# def favorite(request, album_id):
#     album = get_object_or_404(Album, id=album_id)
#     try:
#         selected_song = album.song_set.get(id=request.POST['song'])
#     except(KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#             'album': album,
#             'error_message': "You did not select a valid song",
#         })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'album': album})


# class CreateAlbum(CreateView):
#     model = Album
#     fields = ['artist', 'title', 'genre', 'logo']
#     # No template_name is needed here because the template "album_form.html" is the
#     # default template these view classes use. It automatically looks up what model
#     # it is using (Album in this case) and then looks for "album_form" in the templates folder.
#     # The template must be in this form to work: <model>_form.html
#
#
# class UserFormView(View):
#     form_class = UserForm
#     template_name = 'music/registration_form.html'
#
#     # display blank form
#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {'form': form})
#
#     # process form data
#     def post(self, request):
#         form = self.form_class(request.POST)
#
#         if form.is_valid():
#             user = form.save(commit=False)
#
#             # cleaned (normalized) data
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user.set_password(password)
#             user.save()
#
#             # returns User objects if credentials are correct
#             user = authenticate(username=username, password=password)
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)    # attaches a session automatically
#                     return redirect('music:index')
#
#         return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/registration_login_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Albums{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'music/styles.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'music/js/controller.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Home</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="search" value="">
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>

                    <li class="">
                        {% if user.is_authenticated %}
                            <a href="{% url 'music:logout' %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Logout
                            </a>
                        {% else %}
                            <a href="{% url 'music:register' %}" id="login_register_logout_btn">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Register/Login
                            </a>
                        {% endif %}
                    </li>
                </ul>

            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album.title }} - Details{% endblock %}

{% block body %}
    <img src="{{ album.logo }}" width="300px" height="300px">

    <h1>{{ album.title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    {% for song in album.song_set.all %}
            <label for="{{ song.id }}">
                {{ song.title }}
            </label><br>
        {% endfor %}
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    {% if user.is_authenticated %}
        <span>Hello, {{ user.username }}!</span>
        {% if albums %}
            <h3>My Albums</h3>
            <ul>
                {% for album in albums %}
                <li><a href="{% url 'music:detail' album.id %}">{{ album.title }}</a></li>
                {% endfor %}
            </ul>

        {% else %}
            <h3>Look like you have no albums here! Please add some.</h3>
        {% endif %}
    {% else %}
        <h2>Please <a href="{% url 'music:login' %}">login</a> to view albums</h2>
    {% endif %}
{% endblock %}

music/templates/music/login_form.html
{% extends 'music/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row" id="login">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Login</h3>
                    {% comment %}{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}{% endcomment %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {% if error_message %}
                                <div class="col-sm-offset-2 col-sm-10">
                                <span class="text-danger small">{{error_message}}</span>
                                </div>
                            {% endif %}
                            <label class="control-label col-sm-2">Username</label>
                            <div class="col-sm-10">
                                <input type="text" name="username" value="{{ username }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Password</label>
                            <div class="col-sm-10">
                                <input type="password" name="password">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                                <span >Don't have an account? <a href="{% url 'music:register' %}" >Register here</a></span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/register_template.html
{% for field in form %}
    <div class="form-group">
        {% comment %}<div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>{% endcomment %}
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row" id="register">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            {% if username_error %}
                            <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{username_error}}</span>
                            </div>
                            {% endif %}
                            <label class="control-label col-sm-2">Username</label>
                            <div class="col-sm-10"><input type="text" name="username" value="{{ username }}"></div>
                        </div>

                        <div class="form-group">
                            {% if email_error %}
                            <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{email_error}}</span>
                            </div>
                            {% endif %}
                            <label class="control-label col-sm-2">Email</label>
                            <div class="col-sm-10"><input type="email" name="email" value="{{ email }}"></div>
                        </div>

                        <div class="form-group">
                            {% if password_error %}
                            <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{password_error}}</span>
                            </div>
                            {% endif %}
                            <label class="control-label col-sm-2">Password</label>
                            <div class="col-sm-10"><input type="password" name="password"></div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Register</button>&nbsp;
                                <span >Already have an account? <a href="{% url 'music:login' %}">Login here</a></span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/registration_login_template.html
{% for field in form %}
    <div class="form-group">
        {% comment %}<div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>{% endcomment %}
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}